extends MainLoop

# DO NOT EDIT THIS FILE DIRECTLY
# Generated via convo_parser.py, and used to generate tres file.

# .zshrc has alias /Applications/Godot4.4.app/Contents/MacOS/Godot
# Run with godot4 --headless --script res://dialog/tools/SCRIPT.gd
func _initialize():
	print("Generating dialogs...")
	var res = build()
	ResourceSaver.save(res, "res://dialog/SCRIPT.tres")
	print("Saved dialog.tres")

func _process(_delta):
	return true

func build():
	var collection = DialogTreeCollection.new()
	var trees: Dictionary[String, DialogState] = {}
	trees["Count_A"] = DialogState.create(
		'Player',
		['thought1', 'thought2'],
		['Hello I am the player, I do not get a choice in what to say here'],
		['Hello I am the player, I do not get a choice in what to say here'],
		[
			DialogState.create(
				'Count_A',
				[],
				['Hello I am The Count, and this is conversation A'],
				['Hello I am The Count, and this is conversation A'],
				[
					DialogState.create(
						'Count_A',
						[],
						['I am saying two things, with a pause.'],
						['I am saying two things, with a pause.\nBut this is said without a pause'],
						[
							DialogState.create(
								'Player',
								[],
								['Hello The Count, I think you are an interesting person, or whatever you are, and I hope to get to know you more over the course of the weekend.', 'BBB'],
								['Hello The Count, I think you are an interesting person, or whatever you are, and I hope to get to know you more over the course of the weekend.', 'BBB'],
								[
									DialogState.create(
										'Count_A',
										[],
										['asdfjilk'],
										['asdfjilk'],
										[
											null
										],
										['commands'],
									),
									DialogState.create(
										'Player',
										[],
										['CCC'],
										['CCC'],
										[
											DialogState.create(
												'Count_A',
												[],
												['upiopououi'],
												['upiopououi'],
												[
													null
												],
												[],
											),
										],
										[],
									),
								],
								[],
							),
						],
						[],
					),
				],
				[],
			),
		],
		[],
	)
	collection.trees = trees
	return collection
