extends MainLoop

# DO NOT EDIT THIS FILE DIRECTLY
# Generated via convo_parser.py, and used to generate tres file.

# .zshrc has alias /Applications/Godot4.4.app/Contents/MacOS/Godot
# Run with godot4 --headless --script res://dialog/tools/SCRIPT.gd
func _initialize():
	print("Generating dialogs...")
	var res = build()
	ResourceSaver.save(res, "res://dialog/SCRIPT.tres")
	print("Saved dialog.tres")

func _process(_delta):
	return true

func build():
	var collection = DialogTreeCollection.new()
	var trees: Dictionary[String, DialogState] = {}
	trees["Count_A3"] = DialogState.create(
		'Player',
		[],
		['Hello, Count A, third Counversation'],
		['Hello, Count A, third Counversation'],
		[
			DialogState.create(
				'Count_A3',
				[],
				['Lemme get your number 👀'],
				['Lemme get your number 👀'],
				[
					null
				],
				[],
			),
		],
		[],
	)
	trees["Count_A1"] = DialogState.create(
		'Player',
		['thought1', 'thought2'],
		['Hello I am the player, I do not get a choice in what to say here'],
		['Hello I am the player, I do not get a choice in what to say here'],
		[
			DialogState.create(
				'Count_A1',
				[],
				['Hello I am The Count A, and this is conversation 1'],
				['Hello I am The Count A, and this is conversation 1'],
				[
					DialogState.create(
						'Count_A1',
						[],
						['I am saying two things, with a pause.'],
						['I am saying two things, with a pause.\nBut this is said without a pause'],
						[
							DialogState.create(
								'Player',
								[],
								['Hello The Count, I think you are an interesting person, or whatever you are, and I hope to get to know you more over the course of the weekend.', 'BBB'],
								['Hello The Count, I think you are an interesting person, or whatever you are, and I hope to get to know you more over the course of the weekend.', 'BBB'],
								[
									DialogState.create(
										'Count_A1',
										[],
										['asdfjilk'],
										['asdfjilk'],
										[
											null
										],
										['commands'],
									),
									DialogState.create(
										'Player',
										[],
										['CCC'],
										['CCC'],
										[
											DialogState.create(
												'Count_A1',
												[],
												['upiopououi'],
												['upiopououi'],
												[
													null
												],
												[],
											),
										],
										[],
									),
								],
								[],
							),
						],
						[],
					),
				],
				[],
			),
		],
		[],
	)
	trees["Count_C1"] = DialogState.create(
		'Player',
		['thought1', 'thought2'],
		['Hello I am the player, I do not get a choice in what to say here'],
		['Hello I am the player, I do not get a choice in what to say here'],
		[
			DialogState.create(
				'Count_C1',
				[],
				['Hello I am The Count C, and this is conversation 1'],
				['Hello I am The Count C, and this is conversation 1'],
				[
					null
				],
				[],
			),
		],
		[],
	)
	trees["Count_C3"] = DialogState.create(
		'Player',
		[],
		['Hello, Count C, third Counversation'],
		['Hello, Count C, third Counversation'],
		[
			DialogState.create(
				'Count_C3',
				[],
				['Lemme get your number 👀'],
				['Lemme get your number 👀'],
				[
					null
				],
				[],
			),
		],
		[],
	)
	trees["Count_A2"] = DialogState.create(
		'Player',
		[],
		['Hello, Count A, Second Counversation'],
		['Hello, Count A, Second Counversation'],
		[
			DialogState.create(
				'Count_A2',
				[],
				['Hello again'],
				['Hello again'],
				[
					null
				],
				[],
			),
		],
		[],
	)
	trees["Count_C2"] = DialogState.create(
		'Player',
		[],
		['Hello, Count C, Second Counversation'],
		['Hello, Count C, Second Counversation'],
		[
			DialogState.create(
				'Count_C2',
				[],
				['Hello again'],
				['Hello again'],
				[
					null
				],
				[],
			),
		],
		[],
	)
	trees["Count_B3"] = DialogState.create(
		'Player',
		[],
		['Hello, Count B, third Counversation'],
		['Hello, Count B, third Counversation'],
		[
			DialogState.create(
				'Count_B3',
				[],
				['Lemme get your number 👀'],
				['Lemme get your number 👀'],
				[
					null
				],
				[],
			),
		],
		[],
	)
	trees["Count_B1"] = DialogState.create(
		'Player',
		['thought1', 'thought2'],
		['Hello I am the player, I do not get a choice in what to say here'],
		['Hello I am the player, I do not get a choice in what to say here'],
		[
			DialogState.create(
				'Count_B1',
				[],
				['Hello I am The Count B, and this is conversation 1'],
				['Hello I am The Count B, and this is conversation 1'],
				[
					null
				],
				[],
			),
		],
		[],
	)
	trees["Count_B2"] = DialogState.create(
		'Player',
		[],
		['Hello, Count B, Second Counversation'],
		['Hello, Count B, Second Counversation'],
		[
			DialogState.create(
				'Count_B2',
				[],
				['Hello again'],
				['Hello again'],
				[
					null
				],
				[],
			),
		],
		[],
	)
	collection.trees = trees
	return collection
